<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Provider\Authy\Auth */
?>
<form action="<?php /* @escapeNotVerified */
echo $block->getPostUrl() ?>" method="post" id="tfa-form" data-mage-init='{"form": {}, "validation": {}}'
      autocomplete="off">
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */
    echo $block->getFormKey() ?>"/>

    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?php /* @escapeNotVerified */
                echo __('2FA - Authy Auth') ?></span></legend>
        <br/>

        <?php echo $block->getBlockHtml('formkey') ?>

        <div id="authy-actions-list">
            <h3><?php echo __('Verification methods:') ?></h3>

            <button
                    onclick="authy.runOnetouch()"
                    type="button"
                    class="action-primary">
                <span><?php /* @escapeNotVerified */
                    echo __('Use one touch') ?></span>
            </button>

            <button
                    onclick="authy.runSendCode('token')"
                    type="button"
                    class="action-primary">
                <span><?php /* @escapeNotVerified */
                    echo __('Use authy token') ?></span>
            </button>

            <br/>
            <h3><?php echo __('Emergency methods:') ?></h3>

            <button
                    onclick="authy.runSendCode('sms')"
                    type="button"
                    class="action-default">
                <span><?php /* @escapeNotVerified */
                    echo __('Send me a code via SMS') ?></span>
            </button>

            <button
                    onclick="authy.runSendCode('call')"
                    type="button"
                    class="action-choose">
                <span><?php /* @escapeNotVerified */
                    echo __('Send me a code via phone call') ?></span>
            </button>
        </div>

        <div id="authy-one-touch">
            <img class="loading"
                 src="<?php echo $block->getViewFileUrl('MSP_TwoFactorAuth::images/loading.gif') ?>"/>
            <div id="authy-one-touch-send"><?php echo __('Sending push notification...') ?></div>
            <div id="authy-one-touch-wait"><?php echo __('Waiting for approval...') ?></div>
        </div>

        <div id="authy-one-touch-login">
            <img class="loading"
                 src="<?php echo $block->getViewFileUrl('MSP_TwoFactorAuth::images/logging.gif') ?>"/>
            <div><?php echo __('Access granted, redirecting you to Magento...') ?></div>
        </div>

        <div class="admin__field _required field-tfa_code authy-request-code">
            <label for="tfa_code" class="admin__field-label"><span><?php /* @escapeNotVerified */
                    echo __('Code') ?></span></label>
            <div class="admin__field-control">
                <input
                        id="tfa_code"
                        class="admin__control-text"
                        type="password"
                        name="tfa_code"
                        autofocus
                        value=""
                        data-validate="{required:true}"
                        placeholder="<?php /* @escapeNotVerified */
                        echo __('Your code') ?>"/>
            </div>
        </div>

        <div class="authy-request-code">
            <?php echo $block->getChildHtml('trust-device') ?>
        </div>
        <br/>

        <div class="form-actions authy-request-code">
            <div class="actions">
                <button
                        type="submit"
                        class="action-login action-primary">
                    <span><?php /* @escapeNotVerified */
                        echo __('Confirm') ?></span>
                </button>
            </div>
        </div>

        <a id="authy-switch-method" href="#"
           onclick="authy.switchAnotherMethod()"><?php echo __('Switch to another method') ?></a>
    </fieldset>

    <br/>
    <?php echo $block->getChildHtml('change-provider') ?>
</form>

<script type="text/javascript">
    require(['jquery'], function ($) {
        window.authy = {
            waitForOneTouchApprovalTimeout: 0,

            stopWaitingApproval: function () {
                if (this.waitForOneTouchApprovalTimeout) {
                    window.clearTimeout(this.waitForOneTouchApprovalTimeout);
                    this.waitForOneTouchApprovalTimeout = 0;
                }
            },

            setMethodSelectVisibility: function (status) {
                $('#authy-actions-list').css('display', status ? 'block' : 'none');
                $('#authy-switch-method').css('display', status ? 'none' : 'block');

                if (status) {
                    this.stopWaitingApproval();
                    this.setCodeRequestVisibility(false);
                    this.setOneTouchVisibility(false);
                }
            },

            setOneTouchVisibility: function (status) {
                $('#authy-one-touch').css('display', status ? 'block' : 'none');
            },

            setCodeRequestVisibility: function (status) {
                $('.authy-request-code').css('display', status ? 'block' : 'none');
            },

            runSendCode: function (via) {
                this.setMethodSelectVisibility(false);
                this.setCodeRequestVisibility(true);

                if (via !== 'token') {
                    var tfa_trust_device = $('#tfa_trust_device') ? $('#tfa_trust_device')[0].checked : false;
                    var me = this;
                    $.getJSON('<?php echo $block->getTokenRequestUrl() ?>?via=' + via + '&tfa_trust_device=' + tfa_trust_device)
                        .fail(function (res) {
                            alert('There was an error trying to contact Authy services');
                            me.switchAnotherMethod();
                        });
                }
            },

            runOnetouch: function () {
                this.stopWaitingApproval();

                this.setMethodSelectVisibility(false);
                this.setOneTouchVisibility(true);

                $('#authy-one-touch-send').css('display', 'block');
                $('#authy-one-touch-wait').css('display', 'none');

                var me = this;
                var tfa_trust_device = $('#tfa_trust_device') ? $('#tfa_trust_device')[0].checked : false;
                $.getJSON('<?php echo $block->getOneTouchUrl() ?>?tfa_trust_device=' + tfa_trust_device)
                    .done(function (res) {
                        me.waitForOneTouchApproval();
                    })
                    .fail(function (res) {
                        alert('There was an error trying to contact Authy services');
                        me.switchAnotherMethod();
                    });
            },

            waitForOneTouchApproval: function () {
                $('#authy-one-touch-send').css('display', 'none');
                $('#authy-one-touch-wait').css('display', 'block');

                var me = this;
                $.getJSON('<?php echo $block->getOneTouchVerifyUrl() ?>')
                    .done(function (res) {
                        if (res['status'] === 'retry') {
                            me.waitForOneTouchApprovalTimeout = window.setTimeout(function () {
                                me.waitForOneTouchApproval();
                            }, 1000);
                        } else if (res['status'] === 'expired') {
                            alert('<?php echo $block->escapeJsQuote(__('Your request has been expired')) ?>');
                            me.switchAnotherMethod();
                        } else if (res['status'] === 'denied') {
                            alert('<?php echo $block->escapeJsQuote(__('Your request has been rejected')) ?>');
                            me.switchAnotherMethod();
                        } else if (res['status'] === 'approved') {
                            $('#authy-one-touch').css('display', 'none');
                            $('#authy-one-touch-login').css('display', 'block');
                            self.location.href = '<?php echo $this->getSuccessUrl() ?>';
                        }
                    })
                    .fail(function (res) {
                        alert('There was an error trying to contact Authy services');
                        this.switchAnotherMethod();
                    });
            },

            switchAnotherMethod: function () {
                this.setMethodSelectVisibility(true);
            }
        }
    });
</script>
