<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Provider\Authy\Configure */
$countries = $block->getCountriesList();
?>
<form
        action="<?php /* @escapeNotVerified */ echo $block->getPostUrl() ?>"
        method="post"
        data-mage-init='{"form": {}, "validation": {}}'
        autocomplete="off"
>
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />

    <fieldset class="admin__fieldset">
        <legend class="admin__legend">
            <span><?php /* @escapeNotVerified */ echo __('2FA - Authy') ?></span>
        </legend><br/>

        <h3><?php echo __('Please register yourself to Authy') ?></h3>

        <div class="admin__field _required field-tfa_phone_prefix">
            <label for="tfa_country" class="admin__field-label">
                <span><?php /* @escapeNotVerified */ echo __('Country') ?></span>
            </label>
            <div class="admin__field-control">
                <select
                    id="tfa_country"
                    class="admin__control-select"
                    name="tfa_country"
                    data-validate="{required:true}">

                    <?php foreach ($countries as $country) : ?>
                        <option value="<?php echo $country['dial_code'] ?>"><?php echo $country['name'] ?></option>
                    <?php endforeach; ?>

                </select>
            </div>
        </div>

        <div class="admin__field _required field-tfa_phone">
            <label for="tfa_phone" class="admin__field-label">
                <span><?php /* @escapeNotVerified */ echo __('Phone number') ?></span>
            </label>
            <div class="admin__field-control">
                <input
                        id="tfa_phone"
                        class="admin__control-text"
                        type="text"
                        name="tfa_phone"
                        autofocus
                        value=""
                        data-validate="{required:true, 'validate-phone':true}"
                        placeholder="<?php /* @escapeNotVerified */ echo __('Phone number') ?>"/>
            </div>
        </div>

        <div class="admin__field _required field-tfa_method">
            <label for="tfa_phone_action" class="admin__field-label">
                <span><?php /* @escapeNotVerified */ echo __('Verification method') ?></span>
            </label>
            <div class="admin__field-control">
                <select
                        id="tfa_phone_action"
                        class="admin__control-select"
                        name="tfa_method"
                        data-validate="{required:true}">

                    <option value="sms" selected><?php echo __('Send me an SMS') ?></option>
                    <option value="call"><?php echo __('Call me') ?></option>

                </select>
            </div>
        </div>

        <div class="form-actions">
            <div class="actions">
                <button
                    type="submit"
                    class="action-login action-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Verify')?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>