<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Provider\Authy\Verify */
$verifyInfo = $block->getVerifyInfo();
?>
<form
        action="<?php /* @escapeNotVerified */ echo $block->getPostUrl() ?>"
        method="post"
        data-mage-init='{"form": {}, "validation": {}}'
        autocomplete="off"
>
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />

    <fieldset class="admin__fieldset">
        <legend class="admin__legend">
            <span><?php /* @escapeNotVerified */ echo __('2FA - Authy') ?></span>
        </legend><br/>
        <p>
            <strong><?php echo $verifyInfo['message'] ?></strong><br />
            <a href="<?php echo $block->getConfigUrl() ?>">
                <?php echo __('Click here to change your phone number') ?>
            </a>
        </p><br />

        <div class="admin__field _required field-tfa_verify">
            <label for="tfa_verify" class="admin__field-label">
                <span><?php /* @escapeNotVerified */ echo __('Verification code') ?></span>
            </label>
            <div class="admin__field-control">
                <input
                        id="tfa_verify"
                        class="admin__control-text"
                        type="text"
                        name="tfa_verify"
                        autofocus
                        value=""
                        data-validate="{required:true}"
                        placeholder="<?php /* @escapeNotVerified */ echo __('Verification code') ?>"/>
            </div>
        </div>

        <div class="form-actions">
            <div class="actions">
                <button
                    type="submit"
                    class="action-login action-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Verify')?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>

<script type="text/javascript">
    window.setTimeout(function () {
      self.location.href='<?php echo $block->getConfigUrl() ?>';
    }, <?php echo $verifyInfo['seconds_to_expire'] * 1000 ?>);
</script>