<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Provider\Google\Auth */
?>
<form action="<?php /* @escapeNotVerified */ echo $block->getPostUrl() ?>" method="post" id="tfa-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off">
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />

    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('2FA - Google Auth') ?></span></legend><br/>

        <?= $block->getBlockHtml('formkey')?>

        <div class="admin__field _required field-tfa_code">
            <label for="tfa_code" class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Authenticator code') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="tfa_code"
                    class="admin__control-text"
                    type="password"
                    name="tfa_code"
                    autofocus
                    value=""
                    data-validate="{required:true}"
                    placeholder="<?php /* @escapeNotVerified */ echo __('Your code') ?>"/>
            </div>
        </div>
        <?= $block->getChildHtml('trust-device') ?>

        <div class="form-actions">
            <div class="actions">
                <button
                    type="submit"
                    class="action-login action-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Confirm')?></span>
                </button>
            </div>
        </div>
    </fieldset>

    <?= $block->getChildHtml('change-provider') ?>

    <p><?= __('by <a href="http://www.magespecialist.it" target="_blank">MageSpecialist</a> Security Suite') ?></p>
</form>