<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Provider\U2fKey\Configure */
?>
<form>
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('2FA - U2F key registration') ?></span></legend>
        <br/>
        <div id="u2f-touch-key">
            <h3><?= __('Plug in your U2F key, then touch button') ?></h3>
            <img src="<?php echo $block->getViewFileUrl('MSP_TwoFactorAuth::images/u2f/touch.png') ?>" />
        </div>

        <div id="u2f-login">
            <img class="loading" src="<?php echo $block->getViewFileUrl('MSP_TwoFactorAuth::images/logging.gif') ?>"/>
            <h3><?php echo __('Approved, redirecting you to Magento...') ?></h3>
        </div>

    </fieldset>

    <p><?php echo __('by <a href="http://www.magespecialist.it" target="_blank">MageSpecialist</a> Security Suite') ?></p>
</form>

<script>
  require(['jquery', 'MSP_TwoFactorAuth/js/u2f'], function ($) {
    function waitForTouch() {
      var registerData = <?= $block->getRegisterData() ?>;
      var requestData = registerData[0];
      var signs = registerData[1];

      u2f.register(
        [requestData],
        signs,
        function (registerResponse) {
          $.post('<?= $block->getConfigurePostUrl() ?>', {
            'request': requestData,
            'response': registerResponse
          }).done(function (res) {
            if (res['success']) {
              $('#u2f-login').css('display', 'block');
              $('#u2f-touch-key').css('display', 'none');
              self.location.href='<?= $block->getSuccessUrl() ?>'
            } else {
              waitForTouch();
            }
          }).fail(function () {
            alert('<?= $block->escapeJsQuote('Unable to register your device') ?>');
          })
        }, 120
      );
    }

    waitForTouch();
  });
</script>


