<?php
/**
 * IDEALIAGroup srl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@idealiagroup.com so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2016 IDEALIAGroup srl (http://www.idealiagroup.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Activate */
?>
<form action="<?php /* @escapeNotVerified */ echo $block->getPostUrl() ?>" method="post" id="tfa-form" data-mage-init='{"form": {}, "validation": {}}' autocomplete="off">
    <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />

    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('Two Factor Auth') ?></span></legend><br/>

        <img src="<?php echo $block->getQrCodeUrl()?>" />

        <p><?php echo __('Scan this code with your authenticator app and insert your code to confirm.') ?></p>

        <?php echo $block->getBlockHtml('formkey')?>

        <div class="admin__field _required field-tfa_code">
            <label for="tfa_code" class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Authenticator code') ?></span></label>
            <div class="admin__field-control">
                <input
                    id="tfa_code"
                    class="admin__control-text"
                    type="text"
                    name="tfa_code"
                    autofocus
                    value=""
                    data-validate="{required:true}"
                    placeholder="<?php /* @escapeNotVerified */ echo __('Your code') ?>"/>
            </div>
        </div>

        <div class="form-actions">
            <div class="actions">
                <button
                    type="submit"
                    class="action-login action-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Confirm')?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>