<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\TrustDevice */
$canShow = $block->canShowTrustDevice();
?>
<?php if ($canShow) : ?>
<div class="admin__field field-tfa_trusted">
    <input id="tfa_trust_device" name="tfa_trust_device" value="1" type="checkbox" class="admin__control-checkbox" />&nbsp;
    <label for="tfa_trust_device"><span><?php /* @escapeNotVerified */ echo __('Trust this device, do not ask again') ?></span></label>
</div>
<?php endif ?>
