<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_TwoFactorAuth
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \MSP\TwoFactorAuth\Block\Provider\Duo\Auth */
?>
<form>
    <fieldset class="admin__fieldset">
        <iframe id="duo_iframe"
                data-host="<?php echo $this->getApiHost(); ?>"
                data-sig-request="<?php echo $this->getSignature(); ?>"
                data-post-action="<?php echo $this->getPostAction(); ?>"
        ></iframe>
        <script type="text/javascript">
          require(['MSP_TwoFactorAuth/js/duo'], function(duo) { duo.init(); });
        </script>
    </fieldset>

    <?php echo $block->getChildHtml('change-provider') ?>

    <p><?php echo __('by <a href="http://www.magespecialist.it" target="_blank">MageSpecialist</a> Security Suite') ?></p>
</form>